# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# 构建阶段
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# 生产阶段
FROM node:18-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json ./

RUN npm install --production

EXPOSE 3000

CMD ["npm", "start"]
