name: Test Release

on:
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Create Test Release
        uses: softprops/action-gh-release@v1
        with:
          # 只包含源代码压缩包，不包含单独的 JS 文件
          generate_release_notes: true
          draft: true
          prerelease: true
          tag_name: v0.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}